### ISSUE TITLE
Problem with default build on Japanese Windows 10. VC2019, latest CMake : code page 932 issues.

### ISSUE THREAD

**Issue by Romain-Piquois** [nfrechette/acl#260] opened 2020-01-23 08:21 UTC
Hello. I'm having problem with building ACL for windows.
I'll probably fix it by disabling warning treated as errors but made an issue FYI :

Platform : VC 2019
CMake : updated to latest version before build.
Did properly all git submodule update --init first as documented.

My machine is japanese Windows 10.
(Note : my OS language is set to english but I bought and made it while in japan)

Having a lot of those :
W:\acl\external\catch2\single_include\catch2\catch.hpp(3243): warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss (compiling source file W:\acl\tests\sources\core\test_bit_manip
_utils.cpp) [W:\acl\build\tests\main_generic\acl_unit_tests.vcxproj]

(Warning treated as error obviously stop the build)

I temporarely removed the warning treated as errors and end up with just the following warning now.
W:\acl\tools\acl_compressor\sources\acl_compressor.cpp(631): warning C4996: 'rtm::scalar_near_equal': was declared deprecated
W:\acl\external\rtm\includes\rtm/scalarf.h(368): note: see declaration of 'rtm::scalar_near_equal'
W:\acl\tools\acl_compressor\sources\acl_compressor.cpp(632): warning C4996: 'rtm::scalar_near_equal': was declared deprecated

Warmest regards,
Romain

**Comment by nfrechette** [comment] 2020-01-23 15:00
Thank you for reporting this!
Which branch did you use, master?
Which version of VS 2019 are you using?

The catch2 code looks perfectly normal to me. I am wondering if this is perhaps a vs2019 compiler bug. As of 3 days ago, AppVeyor uses VS2019 16.4.3 which CI ran with last night with the develop branch (but master hasn't run in some time). If your version is newer, I'll update and try locally as well.

For the deprecation, I'll take a look tonight as well. For the time being, ignoring the deprecation warnings is fine and safe but it is odd that the CI builds haven't picked it up.

**Comment by Romain-Piquois** [comment] 2020-01-23 15:17
Hi !

I have tried both dev / master.
My VS 2019 is 16.3.3 
Not sure what is exactly doing that in your particular case, as the text for your asserts look just fine without unsupported characters. ( but I have seen that warning happen sometime when people modified my files on non windows machine and commit back into my projects )

Anyway, it was not much about filing a bug but making you aware that some user may have this issue. ;-)

**Comment by nfrechette** [comment] 2020-01-23 20:26
For the code page issue, can you try adding the following line `target_compile_options(${PROJECT_NAME} PRIVATE /utf-8)` to this file: `W:\acl\tests\main_generic\CMakeLists.txt`? Add the line under the `if(MSVC)` scope on line 33.

It appears that the catch2 header contains unicode characters but the header does not contain a UTF-8 BOM. As such, the compiler uses your locale (japanese) and attempts to convert the unicode characters to japanese characters and fails. If that switch resolves your issue, I will submit that fix into develop and reference this issue with the commit message and I'll also open an issue with catch2.

With ACL and my other projects, I use an .editorconfig file to ensure all files use UTF-8 but no unicode characters are used and it seems that it does not add a BOM either.

**Comment by nfrechette** [comment] 2020-01-23 20:33
For the `scalar_near_equal` warning, in `develop` the issue should be fixed, the `develop` branch of RTM has deprecated that function but the `master` branch of ACL (v1.3.0) uses RTM 1.1.0 which has not deprecated that function. I suspect that if you get that warning, you are using ACL 1.3 with the develop branch of RTM. The next version of ACL will use the next version of RTM with that new deprecation warning. As long as you use the version matching the release, there should not be a warning here. If you wish to use a newer RTM version with ACL 1.3, you can, but you will need to either add a `threshold` argument to fix the warning or you can continue to ignore the warning since it is only present in a tool used for regression testing.

**Comment by Romain-Piquois** [comment] 2020-01-23 21:35
I'll have a look tomorrow or this week-end. Thanks again.

**Comment by nfrechette** [comment] 2020-02-17 17:43
Did you get the chance to try the proposed fix in commit 4e08dbb?

**Comment by nfrechette** [comment] 2020-02-18 16:34
It seems like the unicode issue has been fixed in a later version of Catch2. I will update it which should resolve that for the develop branch.

**Closed** 2020-02-22 13:16 UTC
Labels: bug

**Comment by nfrechette** [comment] 2021-02-22 14:38
@all-contributors add @Romain-Piquois as bug reports
