### ISSUE TITLE
Support of UWP ARM64 platform

### ISSUE THREAD

**Issue by johanlindfors** [nfrechette/acl#188] opened 2019-03-28 12:22 UTC
Trying to generate Visual Studio 2017 project with cmake for ARM64 platform but fails to compile since "warning C4324: 'acl::RigidBone': structure was padded due to alignment specifier"

Any way to get this to work?

/Johan

**Comment by nfrechette** [comment] 2019-03-28 13:29
This for android with NVIDIA CodeWorks? I'll take a look tonight but it was compiling fine the last time I tried it about 2-3 months ago. I'll take a look tonight. UE4 also compiles it fine on ARM64 with NVIDIA codeworks. Are you trying to extend it to a classic android studio cmake project?

**Comment by johanlindfors** [comment] 2019-03-28 13:38
Well, this is actually intended for Universal Windows Platform on ARM64 devices.

**Comment by nfrechette** [comment] 2019-03-28 13:47
That is indeed a platform I haven't tested on, I don't have an ARM UWP platform on hand. That being said, I should be able to figure out how to generate the solution and build to test it out. Usually that warning can be fixed by artificially inserting padding by hand, see `acl::CompressedClip` and `acl::uniformly_sampled::impl::SamplingContext`.

**Comment by nfrechette** [comment] 2019-03-30 23:56
Ok, a fix is in the works, it should land in `develop` in a few hours.

Note that without the fix, while the code should work and compile with some warnings, the NEON intrinsic detection was not working for that platform and as such scalar code was being generated. Although I do not have a device to test with, I made sure that the intrinsics were compiled properly in my fix. Let me know if you have issues or if you have any other feedback, either here in this/other issues or by email. I would also appreciate if you could let me know if the code works as intended on that platform.

If you have a suggestion for a decent device I could purchase to test with, I am also all ears.

I also clarified the documentation to state that there is no setup required to use this library, it is 100% headers and you can just include them and hit the ground running. There is no binary to link/generate.

**Comment by nfrechette** [comment] 2019-04-01 22:20
FYI, a bug was reported to me in the one windows ARM64 code line. Quaternion multiplication will be broken as a result.

**Closed** 2019-04-06 15:38 UTC
Labels: bug, enhancement
